# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-15 20:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'monthly', 'Monthly'), (b'yearly', 'Yearly'), (b'database', 'Database'), (None, None)], default=None, max_length=11)),
                ('braintree_id', models.CharField(default=None, max_length=50)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('monthly_member', 'Is a monthly member'), ('yearly_member', 'Is an yearly member'), ('database_member', 'Can view database')),
            },
        ),
    ]
